# CLASSICAL LSTM EXPERIMENT SUITE
# Purpose: Test different LSTM depths and widths to find optimal ship dynamics modeling.

# 1. Baseline LSTM: Small and fast to verify pipeline integrity
- data: "data/reduce_row_number_absolutes"
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad', 'asv', 'ararad']
  model: "classical"
  predict: "motion"
  hidden_size: 16
  layers: 1
  learning_rate: 0.005
  batch_size: 32
  maxiter: 50      # Epochs in classical mode
  patience: 1000     # Early stopping
  run: 0