- model: 'multihead'
  data: "Waypoint_reduced_absolute"
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad', 'asv', 'ararad']
  optimizer: 'spsa'
  learning_rate: [0.05, 0.001]
  batch_size: 256
  maxiter: 4000
  encoding: 'compact'
  initialization: identity
  run: [0, 1, 2]
  heads_config:
    - features: ['wv', 'sv', 'rarad']
      output_dim: 2
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]
    - features: ['yr', 'asv', 'ararad']
      output_dim: 1
      reps: 5
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: full
      map: [0, 1, 2]
- model: 'multihead'
  data: "Waypoint_reduced_absolute"
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad', 'asv', 'ararad']
  optimizer: 'spsa'
  learning_rate: [0.05, 0.001]
  batch_size: 256
  encoding: 'compact'
  initialization: identity
  run: [0, 1, 2]
  heads_config:
    - features: ['wv', 'sv', 'rarad']
      output_dim: 2
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: linear
      map: [0, 1, 2]
    - features: ['yr', 'asv', 'ararad']
      output_dim: 1
      reps: 5
      encoding: compact
      ansatz: efficientsu2
      entangle: linear
      map: [0, 1, 2]
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: full
      map: [0, 1, 2]
- model: 'multihead'
  data: "Waypoint_reduced_absolute"
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad', 'asv', 'ararad']
  optimizer: 'spsa'
  learning_rate: [0.05, 0.001]
  batch_size: 256
  encoding: 'compact'
  initialization: identity
  run: [0, 1, 2]
  heads_config:
    - features: ['wv', 'sv', 'rarad']
      output_dim: 2
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]
    - features: ['yr', 'asv', 'ararad']
      output_dim: 1
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]