# - window_size: 5
#   data: reduce_dataset
#   select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
#   model: multihead
#   predict: motion
#   optimizer: spsa
#   maxiter: 4000
#   batch_size: 64
#   learning_rate: [0.02, 0.001]
#   perturbation: 0.1
#   weights: [1.0, 1.0, 1.0, 1.0] # Balanced
#   run: [0]
#   heads_config:
#     # Head 1: Surge (Standard)
#     - features: ['wv', 'sv', 'yr', 'rarad']
#       output_dim: 1
#       reps: 2
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular
#       map: [0, 1, 2, 3,-1,-1]
#     # Head 2: Lateral (Merged Sway+YawRate+YawAngle)
#     # Changed from Reps 4 (Too deep) to Reps 2 (Generalization)
#     - features: ['sv', 'yr', 'ya', 'rarad']
#       output_dim: 3
#       reps: 2              
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular
#       map: [0, 1, 2, 3,-1,-1]
- window_size: 5
  data: reduce_dataset
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  batch_size: 64
  learning_rate: [0.02, 0.001]
  perturbation: 0.1
  weights: [1.0, 1.0, 1.0, 1.0]
  run: [0]
  heads_config:
    # Head 1: Surge -> ONLY ['wv', 'sv', 'rarad'] (Matches successful logs)
    - features: ['wv', 'sv', 'rarad']
      output_dim: 1
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]

    # Head 2: Lateral -> Standard
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]

    # Head 3: Yaw Angle -> Standard
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]