# # EXPERIMENT 3: The "RealAmplitudes" (Simpler Gates)
# # Focus: Uses a different Ansatz that has fewer parameters and is easier to train.
# # ==============================================================================
# - window_size: 5
#   data: reduce_dataset
#   select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
#   model: multihead
#   predict: motion
#   optimizer: spsa
#   maxiter: 4000
#   batch_size: 64
#   learning_rate: [0.02, 0.001]
#   perturbation: 0.1
#   weights: [1.0, 1.0, 1.0, 1.0]
#   run: [0]
#   heads_config:
#     # Using 'realamplitudes' for everything. It's robust.
#     - features: ['wv', 'sv', 'yr', 'rarad']
#       output_dim: 1
#       reps: 2
#       encoding: compact
#       ansatz: realamplitudes # <--- CHANGE
#       entangle: circular
#       map: [0, 1, 2, 3,-1,-1]
#     - features: ['sv', 'yr', 'rarad']
#       output_dim: 2
#       reps: 2
#       encoding: compact
#       ansatz: realamplitudes # <--- CHANGE
#       entangle: circular
#       map: [0, 1, 2]
#     - features: ['ya', 'yr', 'rarad']
#       output_dim: 1
#       reps: 1
#       encoding: compact
#       ansatz: realamplitudes # <--- CHANGE
#       entangle: circular
#       map: [0, 1, 2]
- window_size: 5
  data: reduce_dataset
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  batch_size: 64
  learning_rate: [0.02, 0.0005] # Ends lower for finer convergence
  perturbation: 0.01            # <--- REDUCED 10x (Drastically reduces noise)
  weights: [1.0, 1.0, 1.0, 1.0]
  run: [0]
  heads_config:
    # Standard stable config
    - features: ['wv', 'sv', 'yr', 'rarad']
      output_dim: 1
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2, 3,-1,-1]
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]