# - window_size: 5
#   data: reduce_dataset
#   select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
#   model: multihead
#   predict: motion
  
#   optimizer: spsa
#   maxiter: 6000
#   batch_size: 64
#   learning_rate: [0.02, 0.001]
#   perturbation: 0.1
#   weights: [5.0, 1.0, 1.0, 1.0]
#   run: [0]

#   heads_config:
#     # Head 1: Surge
#     - features: ['wv', 'sv', 'yr', 'rarad']
#       output_dim: 1
#       reps: 3
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: full
#       map: [0, 1, 2, 3,-1,-1]

#     # Head 2: Sway
#     - features: ['sv', 'yr', 'rarad']
#       output_dim: 2
#       reps: 3
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: full
#       map: [0, 1, 2]

#     # Head 3: Yaw
#     - features: ['ya', 'yr', 'rarad']
#       output_dim: 1
#       reps: 1
#       encoding: compact
#       ansatz: realamplitudes
#       entangle: full
#       map: [0, 1, 2]
# experiment_definitions/final_balanced.yml
# - window_size: 5
#   data: reduce_dataset
#   select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
#   model: multihead
#   predict: motion
  
#   optimizer: spsa
#   maxiter: 4000           # 4000 is enough for the lighter circuit
#   batch_size: 64
#   learning_rate: [0.02, 0.001]
#   perturbation: 0.1
  
#   # --- FIX 1: BALANCED WEIGHTS ---
#   # We stop forcing the model to memorize the specific speed drop magnitude.
#   weights: [1.0, 1.0, 1.0, 1.0] 
  
#   run: [0]

#   heads_config:
#     # --- FIX 2: LIGHTER CIRCUITS (Better Generalization) ---
#     # Head 1: Surge
#     - features: ['wv', 'sv', 'yr', 'rarad']
#       output_dim: 1
#       reps: 2              # Reduced from 3
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular   # Changed from 'full'
#       map: [0, 1, 2, 3, -1, -1]

#     # Head 2: Sway
#     - features: ['sv', 'yr', 'rarad']
#       output_dim: 2
#       reps: 2              # Reduced from 3
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular   # Changed from 'full'
#       map: [0, 1, 2]

#     # Head 3: Yaw
#     - features: ['ya', 'yr', 'rarad']
#       output_dim: 1
#       reps: 1
#       encoding: compact
#       ansatz: realamplitudes
#       entangle: circular   # Changed from 'full'
#       map: [0, 1, 2]

- window_size: 5
  data: reduce_dataset
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  batch_size: 64
  learning_rate: [0.02, 0.001]
  perturbation: 0.1
  weights: [1.0, 1.0, 1.0, 1.0]
  run: [0]
  heads_config:
    # Head 1: Surge -> Reps 1, Only Speed + Rudder
    - features: ['wv', 'rarad']
      output_dim: 1
      reps: 1              # <--- Super Shallow
      encoding: compact
      ansatz: efficientsu2 # SU2 is better for very shallow circuits
      entangle: circular
      map: [0, 1,-1]

    # Head 2: Lateral -> Reps 2 (Needs more complexity)
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]

    # Head 3: Yaw Angle -> Reps 1
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]