# - window_size: 5
#   data: reduce_dataset
#   select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
#   model: multihead
#   predict: motion
#   optimizer: spsa
#   maxiter: 4000
#   batch_size: 64
#   learning_rate: [0.02, 0.001]
#   perturbation: 0.1
#   weights: [1.0, 1.0, 1.0, 1.0]
#   run: [0]
#   heads_config:
#     # Head 1: Surge -> SUPER SHALLOW (Reps 1)
#     - features: ['wv', 'sv', 'yr', 'rarad']
#       output_dim: 1
#       reps: 1              # <--- Reduced to 1. Prevents memorizing "drops".
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular
#       map: [0, 1, 2, 3,-1,-1]
#     # Others stay at Reps 2
#     - features: ['sv', 'yr', 'rarad']
#       output_dim: 2
#       reps: 2
#       encoding: compact
#       ansatz: efficientsu2
#       entangle: circular
#       map: [0, 1, 2]
#     - features: ['ya', 'yr', 'rarad']
#       output_dim: 1
#       reps: 1
#       encoding: compact
#       ansatz: realamplitudes
#       entangle: circular
#       map: [0, 1, 2]
- window_size: 5
  data: reduce_dataset
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  batch_size: 256          # <--- INCREASED (Smoother optimization)
  learning_rate: [0.02, 0.001]
  perturbation: 0.1
  weights: [1.0, 1.0, 1.0, 1.0]
  run: [0]
  heads_config:
    # Using the standard successful architecture
    - features: ['wv', 'sv', 'yr', 'rarad']
      output_dim: 1
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2, 3,-1,-1]
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 2
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]
    - features: ['ya', 'yr', 'rarad']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: circular
      map: [0, 1, 2]