# ==============================================================================
# EXPERIMENT 1: The "Best of Both" (COBYLA)
# Logic: Combines the Jan 29 Steering success (COBYLA + Full Entanglement)
# with the Minimalist Surge fix (Reps 1, Identity Init) on Mixed Data.
# ==============================================================================
- window_size: 5
  data: reduce_dataset  # CRITICAL: Must contain both 10_10 and 20_20
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  
  # Using COBYLA because it achieved the 0.88 Sway R2
  optimizer: cobyla
  maxiter: 2000         # COBYLA converges faster per step than SPSA
  tol: 0.001
  batch_size: 32        # COBYLA likes stable gradients
  
  # Weights: Focus equally on all
  weights: [1.0, 1.0, 1.0, 1.0]
  
  # Initialize near Identity to help Surge start as "Pass-Through"
  initialization: identity 
  run: [0]

  heads_config:
    # --- HEAD 1: SURGE (The Fix) ---
    # Minimalist: Only Speed + Rudder. Reps 1. 
    # Prevents memorizing the "Big Drop".
    - features: ['wv', 'rarad']
      output_dim: 1
      reps: 1              # <--- Reduced depth
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, -1]

    # --- HEAD 2: LATERAL (The Jan 29 Winner) ---
    # High Expressivity: Reps 3, Full Entanglement
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 3              # <--- Kept high for accuracy
      encoding: compact
      ansatz: efficientsu2 # <--- Strong ansatz
      entangle: full       # <--- Strong entanglement
      map: [0, 1, 2]

    # --- HEAD 3: ANGLE (The Jan 29 Winner) ---
    - features: ['ya', 'yr']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: full
      map: [0, 1,-1]

# ==============================================================================
# EXPERIMENT 2: The "Best of Both" (SPSA Version)
# Logic: Same architecture but with SPSA for comparison/speed.
# ==============================================================================
- window_size: 5
  data: reduce_dataset
  select_features: ['wv', 'sv', 'yr', 'ya', 'rarad']
  model: multihead
  predict: motion
  
  optimizer: spsa
  maxiter: 4000
  batch_size: 64
  learning_rate: [0.02, 0.001]
  perturbation: 0.1
  
  weights: [1.0, 1.0, 1.0, 1.0]
  initialization: identity
  run: [0]

  heads_config:
    # Head 1: Surge (Minimalist Fix)
    - features: ['wv', 'rarad']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, -1]

    # Head 2: Lateral (Jan 29 Config)
    - features: ['sv', 'yr', 'rarad']
      output_dim: 2
      reps: 3
      encoding: compact
      ansatz: efficientsu2
      entangle: full
      map: [0, 1, 2]

    # Head 3: Angle (Jan 29 Config)
    - features: ['ya', 'yr']
      output_dim: 1
      reps: 1
      encoding: compact
      ansatz: realamplitudes
      entangle: full
      map: [0, 1, -1]