- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: &id001 [wv, sv, yr, ya, rarad]
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: &id002 [1.0, 1.0, 1.0, 1.0]
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id003 [0.05, 0.001]
  perturbation: 0.1
  batch_size: 512
  heads_config: &id004
  - features: [wv, sv, rarad]
    output_dim: 1
    reps: 2
    encoding: compact
    ansatz: efficientsu2
    entangle: full
    map: [0, 1, 2]
  - features: [sv, yr, rarad]
    output_dim: 2
    reps: 3
    encoding: compact
    ansatz: efficientsu2
    entangle: full
    map: [0, 1, 2]
  - features: [ya, yr]
    output_dim: 1
    reps: 2
    encoding: compact
    ansatz: realamplitudes
    entangle: full
    map: [0, 1, -1]
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id003
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id003
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id003
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id003
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id005 [0.05, 0.001]
  perturbation: 0.2
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id005
  perturbation: 0.2
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id005
  perturbation: 0.2
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id005
  perturbation: 0.2
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id005
  perturbation: 0.2
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id006 [0.05, 0.001]
  perturbation: 0.05
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id006
  perturbation: 0.05
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id006
  perturbation: 0.05
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id006
  perturbation: 0.05
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id006
  perturbation: 0.05
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id007 [0.05, 0.001]
  perturbation: 0.1
  batch_size: 256
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id007
  perturbation: 0.1
  batch_size: 256
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id007
  perturbation: 0.1
  batch_size: 256
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id007
  perturbation: 0.1
  batch_size: 256
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id007
  perturbation: 0.1
  batch_size: 256
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id008 [0.05, 0.001]
  perturbation: 0.1
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id008
  perturbation: 0.1
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id008
  perturbation: 0.1
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id008
  perturbation: 0.1
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id008
  perturbation: 0.1
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id009 [0.1, 0.005]
  perturbation: 0.25
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id009
  perturbation: 0.25
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id009
  perturbation: 0.25
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id009
  perturbation: 0.25
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id009
  perturbation: 0.25
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id010 [0.01, 0.0005]
  perturbation: 0.05
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id010
  perturbation: 0.05
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id010
  perturbation: 0.05
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id010
  perturbation: 0.05
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id010
  perturbation: 0.05
  batch_size: 1024
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id011 [0.1, 0.001]
  perturbation: 0.15
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id011
  perturbation: 0.15
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id011
  perturbation: 0.15
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id011
  perturbation: 0.15
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id011
  perturbation: 0.15
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id012 [0.03, 0.003]
  perturbation: 0.12
  batch_size: 768
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id012
  perturbation: 0.12
  batch_size: 768
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id012
  perturbation: 0.12
  batch_size: 768
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id012
  perturbation: 0.12
  batch_size: 768
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id012
  perturbation: 0.12
  batch_size: 768
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 1
  learning_rate: &id013 [0.05, 0.0001]
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 2
  learning_rate: *id013
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 3
  learning_rate: *id013
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 4
  learning_rate: *id013
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
- window_size: 5
  data: data/reduce_row_number_absolutes
  save_dir: final_winner_optimization
  select_features: *id001
  model: multihead
  predict: motion
  optimizer: spsa
  maxiter: 4000
  weights: *id002
  initialization: identity
  save_plot: false
  run: 5
  learning_rate: *id013
  perturbation: 0.1
  batch_size: 512
  heads_config: *id004
